[tool.poetry]
name = "remarkable"
version = "0.1.0"
description = ""
authors = ["Gideon Tong <gideon@gideontong.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
