name: Deploy to production

on:
 - workflow_dispatch

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.11
          architecture: x64