name: Deploy to staging

on:
  push:
    branches:
      - 'master'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.11
          architecture: x64